---
title: "wrangle"
author: "Wonjun Choi"
date: "2022-09-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Import Package, results = FALSE}
pacman::p_load(tidyverse, haven, here)
```

```{r}
# df_hosp %>% select(ID) %>% unique()  # n = 7165
```

```{r}
y <-2007
dir_temp <-here('data','temp')
df_reg_add <- read.csv(here(dir_temp,paste0('change_Reg Add_',y,'.csv')))
df_reg_del <- read.csv(here(dir_temp,paste0('change_Reg Add_',y,'.csv')))
df_nonreg_add <- read.csv(here(dir_temp,paste0('change_Nonreg Add_',y,'.csv')))
df_nonreg_del <- read.csv(here(dir_temp,paste0('change_Nonreg Del_',y,'.csv')))
```

```{r}
df_reg_add
```
```{r}
#df_hosp %>% filter(ID==6350011)
```



```{r Cooper data}
dat_cooper <- read_csv(paste0(here(),'/data/cooper-et-al/HC_ext_mergerdata_public.csv'))
```
```{r}
dat_cooper %>% filter(id=='653032B')
```

```{r check each variable}
for (v in variable.names(df_tmp)){
  print(df_tmp %>% select(v) %>% group_by_(v)%>% summarise(n=n()))
}
```
- HOSPN: not unique
- SYSID(matches to health care system file?): not unique
- SYSNAME: not unique, 2833 NA's
- (LAT,LONG): not unique -> see [lat,long is not unique]

```{r sysid is not unique}
df_tmp1 <- df_tmp %>% group_by(SYSID) %>% summarise(n=n()) %>% right_join(df_tmp, by="SYSID")

df_tmp1 %>% filter(n>=2) %>% select(ID, SYSID, n)

# cross-check with cooper -- not meaningful in this stage...
df_tmp2 <- dat_cooper %>% filter(year==2007)
df_tmp2 <- df_tmp2 %>% group_by(sysid) %>% summarise(n=n()) %>% right_join(df_tmp2, by='sysid')

df_tmp2 %>% filter(n>=2) %>% select(id, sysid, n)

df_tmp1 %>% mutate(id=ID) %>% left_join(df_tmp2, by="id") %>% select(id, SYSID, n.x, n.y)
```
seems cooper et al. somehow pooled sysid==2...?

```{r lat,long is not unique}
df_tmp %>% group_by(LAT,LONG) %>% summarise(n=n()) %>% left_join(df_tmp, by=c("LAT","LONG")) %>% filter(n >=2) %>% select(ID, n, LAT, LONG)
```

```{r}
dat_cooper %>% filter(year==2007) %>% nrow()
```


```{r}
dat_cooper %>% filter(year==2007) %>% select(id) %>% unique()
dat_cooper %>% group_by(sysid) %>% summarise(n_cooper=n()) %>% left_join(dat_cooper, by="sysid") %>% select(id, sysid, n_cooper) %>% mutate(ID = id) %>% left_join(df_tmp, by="ID") %>% select(ID, sysid, n_cooper)
```

```{r}
dat_cooper %>% select("id", "sysid", "id_defunct", "id_parent")
```

```{r}
ll <- unique(df_del$ID)
```

```{r}
df_hosp2 %>% names()
```

```{r}
df_hosp%>%names()
```


```{r}
aha_data %>% names()
```

```{r drop columns 'from, previously'}
# just status change: nonreg <-> reg
aha_data %>% 
  filter(readum_from==1 | 
           readum_Previously|
           readum_STATUS==1) %>%
  select(ID,year,add,del,reason)
# aha_data <- aha_data %>% select(-readum_from)
```


```{r drop rows 'Not a hospital'}
aha_data %>% 
  filter(readum_Inpatient==1 | readum_Ambulatory==1 |
           readum_Inpatient==1 | readum_Outpatient==1 |
           readum_Hospice==1 | readum_Not==1 |
           readum_Psychiatric==1 | readum_Behavioral==1 |
           readum_Ambulatory==1 | readum_Nursing==1 |
           readum_Rehabilitation==1 | readum_Urgent==1 |
           readum_Skilled==1 | readum_Developmental==1
           ) %>% 
  select(ID, year, add, del, reason)
li <- aha_data %>%
  filter(readum_Inpatient==1 | readum_Ambulatory==1 |
           readum_Inpatient==1 | readum_Outpatient==1 |
           readum_Hospice==1 | readum_Not==1 |
           readum_Psychiatric==1 | readum_Behavioral==1 |
           readum_Ambulatory==1 | readum_Nursing==1 |
           readum_Rehabilitation==1 | readum_Urgent==1 |
           readum_Skilled==1 | readum_Developmental==1) %>%
  select(ID)
li$ID
# ID_list_to_del = append(ID_list_to_del, li)
```

```{r}
aha_data %>% filter((ID %in% li$ID))
```
```{r}
aha_data %>% filter(ID==6141740) 
# 6080001: deleted in 2013 bc not hospital, but added again.
#  => delete before deletion, and check again

for (id in li) {
  
}
```


```{r ID change}
aha_data %>% 
  filter(readum_ID==1 | readum_System==1 |
           `readum_change-formerly`==1) %>% 
  select(ID, year, add, del, reason)
```


```{r ???}
aha_data %>% 
  filter(readum_Nonregistered==1 |
           readum_Temporarily==1) %>% 
  select(ID, year, add, del, reason)
```

```{r}
aha_data %>% 
  filter(readum_Developmental==1) %>% 
  select(ID, year, add, del, reason)
```



# build-year
```{r}
```
```{r}
ddd <- df_nonreg_add %>% mutate(ID = as.character(ID))

dddd <- df_hosp %>% left_join(ddd, 'ID')
```

```{r if register status changed, in the list}
ff <- df_reg_del %>% mutate(ID = as.character(ID))
why <- df_hosp %>% select(ID) %>% inner_join(ff, by='ID')
```

```{r if register status changed, in the list}
ff <- df_nonreg_del %>% mutate(ID = as.character(ID))
hoxy <- df_hosp %>% select(ID) %>% left_join(ff,by='ID') %>% filter(del==1)
```

