# Shared variable lists for AHA pipeline.
# Used by 1-historic.R, 2-yearly.R, and 3-modern.R to keep the same
# column subset across data sources.

aha_keep <- c(
  "ID", "SYSID", "SYSNAME", "MCRNUM", "NPINUM", "MNAME", "MTYPE", "MLOS", "DTBEG", "DTEND", "FISYR",
  "LAT", "LONG", "MLOCCITY", "MLOCZIP", "MSTATE", "MLOCAD1", "MLOCAD2", "FSTCD", "FCNTYCD",
  "HRRNAME", "HRRCODE", "HSANAME", "HSACODE", "CBSANAME", "CBSACODE", "CBSATYPE",
  "BDTOT", "COMMTY" = "CHC", "EHLTH", "CNTRL", "SERV",
  paste0("MAPP", 1:18),
  "MHSMEMB", "FTEMD", "FTERES", "ADMTOT", "IPDTOT", "MCDDC", "MCRDC", "EXPTOT", "PAYTOT",
  "FTERN", "FTELPN", "FTEH", "NAMMSHOS", "ACLABHOS", "ENDOCHOS", "ENDOUHOUS",
  # Cardiology services. CCLABHOS / OHSRGHOS / CICHOS exist as such in
  # the 1994-2021 WRDS file; older WRDS vintages provide them as
  # CCLAB82 / OHSURG82 / CARDIC82 (renamed in 1-historic.R). The
  # 2014-2024 modern survey drops CCLAB and OHSRG but keeps the adult/
  # pediatric cardiac service indicators.
  "CCLABHOS", "CCLABSYS", "CCLABNET", "CCLABVEN",
  "OHSRGHOS", "OHSRGSYS", "OHSRGNET", "OHSRGVEN",
  "CICHOS", "ACARDHOS", "ACARDSYS", "ACARDNET", "ACARDVEN",
  "PCARDHOS", "PCARDSYS", "PCARDNET", "PCARDVEN",
  "REDSHOS", "CTSCNHOS", "DRADFHOS", "EBCTHOS", "FFDMHOS", "MRIHOS", "IMRIHOS",
  "MSCTHOS", "MSCTGHOS", "PETHOS", "PETCTHOS", "SPECTHOS", "ULTSNHOS",
  "AMBSHOS", "EMDEPHOS", "ICLABHOS", "ADTCHOS", "ADTEHOS", "CHTHHOS", "CAOSHOS",
  "ONCOLHO", "RASTHOS", "IMRTHOS", "CICBD", "NICBD", "NINTBD", "PEDICBD", "OBBD",
  "BROOMHOS", "CARIC", "ESWLHOS", "FITCHOS",
  "IGRTHOS", "SPORTHOS", "WOMHCHOS", "ALCHBD", "BRNBD", "PSYBD", "TRAUMHOS", "PSYCAHOS",
  "AIDSSHOS", "PSYSLSHOS", "PSYEDHOS", "PSYEMHOS", "PSYOPHOS", "PSYPHHOS",
  "ROBOHOS", "ROBOSYS", "ROBONET", "ROBOVEN", "PTONHOS", "PTONSYS", "PTONNET", "PTONVEN",
  "SRADHOS", "SRADSYS", "SRADNET", "SRADVEN",
  "ADULTHOS", "HOSPCHOS", "PATEDHOS", "SOCWKHOS", "VOLSVHOS", "GPWWHOS", "OPHHOS",
  "CPHHOS", "FNDHOS", "EQMHOS", "IPAHOS", "MSOHOS", "ISMHOS",
  "GPWWNET", "OPHNET", "CPHNET", "FNDNET", "EQMNET", "IPANET", "MSONET", "ISMNET",
  "GPWWSYS", "OPHSYS", "CPHSYS", "FNDSYS", "EQMSYS", "IPASYS", "MSOSYS", "ISMSYS",
  "PHYGP", "CAH", "RRCTR", "SCPROV",
  "YEAR", "year"
)

aha_factor <- c(
  "EHLTH", "ACLABHOS",
  "CCLABHOS", "OHSRGHOS", "CICHOS", "ACARDHOS", "PCARDHOS",
  "CTSCNHOS", "DRADFHOS", "EBCTHOS",
  "FFDMHOS", "MRIHOS", "IMRIHOS", "MSCTHOS", "MSCTGHOS",
  "PETHOS", "PETCTHOS", "SPECTHOS", "ULTSNHOS", "AMBSHOS",
  "EMDEPHOS", "ICLABHOS", "ADTCHOS", "CHTHHOS", "CAOSHOS",
  "IMRTHOS", "BROOMHOS", "ESWLHOS", "FITCHOS", "CBSATYPE",
  "IGRTHOS", "SPORTHOS", "WOMHCHOS", "TRAUMHOS", "PSYCAHOS",
  "AIDSSHOS", "PSYEDHOS", "PSYEMHOS", "PSYOPHOS", "PSYPHHOS",
  "ADULTHOS", "HOSPCHOS", "PATEDHOS", "SOCWKHOS", "VOLSVHOS",
  "GPWWHOS", "IPAHOS", "MSOHOS", "ISMHOS", "GPWWNET", "IPANET",
  "MSONET", "ISMNET", "GPWWSYS", "IPASYS", "MSOSYS", "ISMSYS",
  "ID", "NPINUM", "HRRCODE", "SYSID", "FSTCD", "FCNTYCD",
  "CAH", "RRCTR", "SCPROV", "SERV", "COMMTY", "MLOS", "MHSMEMB",
  "ROBOHOS", "ROBOSYS", "ROBONET", "ROBOVEN", "PTONHOS", "PTONSYS", "PTONNET", "PTONVEN",
  "SRADHOS", "SRADSYS", "SRADNET", "SRADVEN"
)

aha_numeric <- c(
  "LAT", "LONG", "SYSTELN", "CICBD", "NICBD", "OBBD", "HSACODE", "CBSACODE",
  "NINTBD", "PEDICBD", "ALCHBD", "BRNBD", "PSYBD"
)

aha_character <- c("DTBEG", "DTEND", "FISYR", "MSTATE", "CBSANAME")
